# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker
trigger:
- develop
resources:
- repo: self
variables:
  tag: '$(Build.BuildId)'
  imageName: 'genomike/logisticaapi'
stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: 'Dockerfile'
        tags: |
          $(imageName):$(tag)
    - task: Docker@2
      displayName: Push an image
      inputs:
        command: push
        repository: $(imageName)
        tags: |
          $(tag)
        containerRegistry: 'DockerHub'