# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker
trigger:
- develop
resources:
- repo: self
variables:
  tag: '$(Build.BuildId)'
  imageName: 'genomike/logisticaapi'
stages:
- stage: Build
  displayName: Build and Push Docker Image
  jobs:
  - job: BuildAndPush
    displayName: Build and Push
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: 'Dockerfile'
        tags: |
          $(imageName):$(tag)
          $(imageName):latest
    - task: Docker@2
      displayName: Push an image
      inputs:
        command: push
        repository: $(imageName)
        tags: |
          $(tag)
          latest
        containerRegistry: 'DockerHub'