# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  branches:
    include:
      - develop

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
  imageName: 'genomike/logisticaapi'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - script: |
        echo "Tag: $(tag)"
      displayName: Print tag
    - script: docker build -t $(imageName):$(tag) .
      displayName: Build and tag Docker image
    - script: docker images
      displayName: List Docker images
    - task: Docker@2
      displayName: Push an image
      inputs:
        command: push
        repository: $(imageName)
        tags: |
          $(tag)
          latest
        containerRegistry: 'DockerHub'
