trigger:
  branches:
    include:
      - develop
pr:
  branches:
    exclude:
      - develop

resources:
- repo: self
variables:
  tag: '$(Build.BuildId)'
  imageName: 'genomike/logisticaapi'
stages:
- stage: Build
  displayName: Build and Push Docker Image
  jobs:
  - job: BuildAndPush
    displayName: Build and Push
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: 'Dockerfile'
        tags: |
          $(imageName):$(tag)
          $(imageName):latest
    - script: docker images
      displayName: List Docker images
    - script: docker tag f8132086a00e $(imageName):$(tag)
      displayName: Tag Docker image
    - task: Docker@2
      displayName: Push an image
      inputs:
        command: push
        repository: $(imageName)
        tags: |
          $(tag)
          latest
        containerRegistry: 'DockerHub'
