apiVersion: apps/v1
kind: Deployment
metadata:
  name: logisticaapi-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logisticaapi
  template:
    metadata:
      labels:
        app: logisticaapi
    spec:
      containers:
      - name: logisticaapi
        image: genomike/logisticaapi:latest
        ports:
        - containerPort: 8085
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Development"
        - name: DEFAULT_CONNECTION
          value: "Server=192.168.0.15,1433;Database=retailproduct;User ID=henry;Password=123456;TrustServerCertificate=True;"