apiVersion: v1
kind: Service
metadata:
  name: logisticaapi-service
spec:
  selector:
    app: logisticaapi
  ports:
    - name: api-port
      protocol: TCP
      port: 8081
      targetPort: 8085
    - name: client-port
      protocol: TCP
      port: 8082
      targetPort: 80
  type: LoadBalancer