apiVersion: v1
kind: Service
metadata:
  name: logisticaapi-service
spec:
  selector:
    app: logisticaapi
  ports:
    - protocol: TCP
      port: 8085
      targetPort: 8085
---
apiVersion: v1
kind: Service
metadata:
  name: logisticaclient-service
spec:
  selector:
    app: logisticaclient
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
