apiVersion: v1
kind: Service
metadata:
  name: {{ include "logisticaapi.fullname" . }}-service
  labels:
    app.kubernetes.io/name: {{ include "logisticaapi.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  selector:
    app: {{ include "logisticaapi.selectorLabels" . }}
  ports:
    - name: api-port
      protocol: TCP
      port: {{ .Values.service.api.port }}
      targetPort: {{ .Values.service.api.targetPort }}
    - name: client-port
      protocol: TCP
      port: {{ .Values.service.client.port }}
      targetPort: {{ .Values.service.client.targetPort }}
  type: {{ .Values.service.type }}
