name: Sync to Azure Repos

on:
  push:
    branches:
      - '**' # Cambia 'main' por la rama que quieras sincronizar
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - '**'

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Setup Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Push changes to Azure Repos
        run: |
          git remote add azure-origin https://qhapaqcode.visualstudio.com/_git/LogisticaApi
          git push azure-origin --all --force
        env:
          AZURE_DEVOPS_PAT: ${{ secrets.AZURE_DEVOPS_PAT }}
