name: Sync to Azure Repos

on:
  push:
    branches:
      - '**'
  create:
    branches:
      - '**'
  delete:
    branches:
      - '**'

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Validate branch name
        if: github.event_name == 'create'
        run: |
          if [[ ! ${{ github.ref }} =~ ^refs/heads/(feature|bugfix|release|hotfix|support|develop|master)/ ]]; then
            echo "Branch name does not follow GitFlow naming conventions."
            exit 1
          fi

      - name: Configure Git
        run: |
          git config --global user.email "genomikel@gmail.com"
          git config --global user.name "Henry"

      - name: Configure Git credentials
        run: |
          git config --global credential.helper store
          echo "https://${{ secrets.AZURE_DEVOPS_PAT }}:x-oauth-basic@qhapaqcode.visualstudio.com/_git/LogisticaApi" > ~/.git-credentials
        env:
          AZURE_DEVOPS_PAT: ${{ secrets.AZURE_DEVOPS_PAT }}

      - name: Push changes to Azure Repos
        run: |
          git remote add azure-origin https://qhapaqcode.visualstudio.com/_git/LogisticaApi
          git push azure-origin --all --force
        env:
          AZURE_DEVOPS_PAT: ${{ secrets.AZURE_DEVOPS_PAT }}

      - name: Delete remote branch
        if: github.event_name == 'delete'
        run: |
          BRANCH_NAME=${GITHUB_REF#refs/heads/}
          git push azure-origin --delete $BRANCH_NAME
        env:
          AZURE_DEVOPS_PAT: ${{ secrets.AZURE_DEVOPS_PAT }}
